- name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Dependencies
        run: |
          pip install flet requests

      - name: Build APK with Flet
        run: |
          flet build apk --project "VisionPass" mobile_app.py

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/apk/*.apk
